<%
  # This file contains ERB-interpreted YAML directives for testkitchen.
  # Secrets are read from the local execution ENV into this file, and
  # passed to the Chef tests via node attributes applied to the test suites.

  AWS_ACCESS_KEY_ID = ENV['AWS_BLUE_ACCESS_KEY_ID'] ||'(ENTER_AWS_ACCESS_KEY_ID)'
  AWS_ACCESS_KEY_SECRET = ENV['AWS_BLUE_SECRET_ACCESS_KEY_ID'] || '(ENTER_AWS_SECRET_ACCESS_KEY)'
  AWS_SSH_KEY_ID = ENV['AWS_SSH_KEY_ID'] || 'default'
  AWS_SSH_KEYPATH = File.expand_path(ENV['AWS_SSH_KEY_PATH'] || "#{ENV['HOME']}/.ssh/id_rsa")

  # support function, needed for inserting raw RSA private key data into YAML
  def yaml_section(hash, indentation)
    YAML.dump(hash).sub(/\A---\s/, '').split("\n").map do |l|
      (" " * indentation) + l
    end.join("\n")
  end
%>

---
driver:
  name: ec2
  aws_access_key_id: <%= AWS_ACCESS_KEY_ID %>
  aws_secret_access_key: <%= AWS_ACCESS_KEY_SECRET %>
  aws_ssh_key_id: <%= AWS_SSH_KEY_ID %>
  ssh_key: <%= AWS_SSH_KEY_PATH %>
  region: us-east-1
  availability_zone: us-east-1c
  flavor_id: <%= ENV['AWS_FLAVOR_ID'] || '(ENTER_AWS_FLAVOR_ID)' %>
  tags:
    created-by: 'test-kitchen'
    launched-by: <%= ENV['USER'] || '(ENTER_USER)' %>

busser:
  sudo: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.4
  data_path: test/shared

platforms:
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
  driver_config:
    image_id: ami-e7582d8e
    username: ubuntu

suites:
- name: default
  run_list:
    - recipe[zookeeper-apt]
    - recipe[chronos]
  attributes:
    chronos:
      jar_source: 'https://s3.amazonaws.com/dl.imedidata.net/chronos/chronos-2.1.0_mesos-0.15.0.jar'
      options:
        default_job_owner: 'rarodriguez@mdsol.com'
    mesos:
      version: '0.15.0'
    java:
      jdk_version: '7'
      install_flavor: 'oracle'
      oracle:
        accept_oracle_download_terms: true
      jdk:
        '7':
          x86_64:
            url: 'http://download.oracle.com/otn-pub/java/jdk/7u25-b15/jdk-7u25-linux-x64.tar.gz'
            checksum: 'f80dff0e19ca8d038cf7fe3aaa89538496b80950f4d10ff5f457988ae159b2a6'

