driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
  - - forwarded_port
    - guest: 8080
      host: 8080
      auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[chronos]
  attributes:
    chronos:
      jar_source: 'https://s3.amazonaws.com/dl.imedidata.net/chronos/chronos-2.1.0_mesos-0.15.0.jar'
    mesos:
      version: '0.15.0'
    java:
      jdk_version: '7'
      install_flavor: 'oracle'
      oracle:
        accept_oracle_download_terms: true
      jdk:
        '7':
          x86_64:
            url: 'http://download.oracle.com/otn-pub/java/jdk/7u25-b15/jdk-7u25-linux-x64.tar.gz'
            checksum: 'f80dff0e19ca8d038cf7fe3aaa89538496b80950f4d10ff5f457988ae159b2a6'
