default['chronos']['home_dir']                                  = '/opt/chronos'
default['chronos']['config_dir']                                = '/etc/chronos'
default['chronos']['log_dir']                                   = '/var/log/chronos'
default['chronos']['jar_source']                                = nil
default['chronos']['user']                                      = 'root'
default['chronos']['group']                                     = 'root'
default['chronos']['java_heap']                                 = "#{(node['memory']['total'].to_i - (node['memory']['total'].to_i/2) ) / 1024}m"

default['chronos']['options']['default_job_owner']              = nil
default['chronos']['options']['disable_after_failures']         = nil
default['chronos']['options']['failover_timeout']               = nil
default['chronos']['options']['failure_retry']                  = nil
default['chronos']['options']['ganglia_group_prefix']           = nil
default['chronos']['options']['ganglia_host_port']              = nil
default['chronos']['options']['ganglia_reporting_interval']     = nil
default['chronos']['options']['hostname']                       = nil
default['chronos']['options']['http_credentials']               = nil
default['chronos']['options']['http_port']                      = nil
default['chronos']['options']['https_port']                     = nil
default['chronos']['options']['leder_max_idle_time']            = nil
default['chronos']['options']['log_config']                     = nil
default['chronos']['options']['mail_from']                      = nil
default['chronos']['options']['mail_password']                  = nil
default['chronos']['optoins']['mail_server']                    = nil
default['chronos']['options']['mail_ssl']                       = nil
default['chronos']['options']['mail_user']                      = nil
default['chronos']['options']['master']                         = nil
default['chronos']['options']['mesos_checkpoint']               = nil
default['chronos']['options']['mesos_framework_name']           = nil
default['chronos']['options']['mesos_role']                     = nil
default['chronos']['options']['mesos_task_cpu']                 = nil
default['chronos']['options']['mesos_task_disk']                = nil
default['chronos']['options']['mesos_task_mem']                 = nil
default['chronos']['optoins']['schedule_horizon']               = nil
default['chronos']['options']['ssl_keystore_password']          = nil
default['chronos']['options']['ssl_keystore_path']              = nil
default['chronos']['options']['user']                           = nil
default['chronos']['options']['mesos_task_mem']                 = nil
default['chronos']['options']['mesos_task_mem']                 = nil
default['chronos']['options']['zk_state']                       = nil
default['chronos']['options']['zk_timeout']                     = nil

default['chronos']['zookeeper_server_list']                     = []
default['chronos']['zookeeper_port']                            = 2181
default['chronos']['zookeeper_path']                            = 'mesos'

default['chronos']['zookeeper_exhibitor_discovery']             = false
default['chronos']['zookeeper_exhibitor_url']                   = nil
